server:
  port: 8090
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: accounts-service
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

#logging:
#  level:
#    org.springframework.transaction: trace
#    org.springframework.kafka.transaction: debug