apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dii-integration
  namespace: default
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: "tcp://broker.emqx.io:1883"
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "false"