version: '3.3'
services:
  # theater-service and its Dapr sidecar
  # zipkin

  ############################
  # theater-service and its Dapr sidecar
  ############################
  theater-service:
    image: exemplar.azurecr.io/theater-service
    build:
      context: theater-service-rest-controller
      dockerfile: Dockerfile
    container_name: theater-service
    environment:
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    ports:
      - 9000:9000
    networks:
      - dii

  theater-service-dapr:
    image: daprio/daprd:edge
    container_name: Dapr.Sidecar-theater-service
    command: ["./daprd",
              "-app-id", "theater-service",
              "-app-port", "9000",
              "-config", "/theater-service-dapr-components/config.yaml",
              "-log-level", "debug",
              "-components-path", "/theater-service-dapr-components"]
    volumes:
      - "./theater-service-dapr-components:/theater-service-dapr-components"
    depends_on:
      - theater-service
    network_mode: "service:theater-service"

  zipkin:
    image: openzipkin/zipkin-slim

networks:
  dii:
    driver: bridge