server:
  port: 9001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service/
          predicates:
            - Path=/api-consumer/**
          filters:
            - RewritePath=/api-consumer/(?<segment>.*),/$\{segment}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
